ncclient/ncclient

ncclient/devices/h3c.py, ncclient/operations/third_party/h3c/__init__.py, ncclient/operations/third_party/h3c/rpc.py, ncclient/xml_.py
H3C device support
support h3c special operate type: cli, action, save, load, rollback, get_bulk, get_bulk_config
=> add H3C support, Support H3C CLI,Action,Get_bulk,Save,Rollback,etc.

ncclient/devices/alu.py
basic ALU support tested against 7750 and XRS
=> add alcatel lucent support

ncclient/operations/rpc.py
We're now using RaiseMode class attributes so change the assert accordingly.
=> Fix RPC.raise_mode

ncclient/devices/huawei.py, ncclient/operations/third_party/h3c/rpc.py, ncclient/operations/third_party/huawei/__init__.py, ncclient/operations/third_party/huawei/rpc.py, ncclient/xml_.py
HuaWei Device support
1. add huawei capabilities
2. add cli, action operation
=> add HuaWei device support

ncclient/operations/rpc.py
=> Will retain the data type of raw, xml

test/unit/test_xml_.py
https://travis-ci.org/vnitinv/ncclient/builds/106692716
=> keeping raw data in test case

ncclient/manager.py, ncclient/transport/errors.py, ncclient/transport/third_party/junos/ioproc.py, test/unit/test_manager.py
with localhost configured in ssh config, it was always pointing to junos specific code
=> junos ioproc changes

ncclient/devices/junos.py, ncclient/transport/session.py, test/unit/transport/test_session.py
Fix #130 
When trying to login with unauthorized user. ncclient hangs for 60 secs and then finally gives capabilities exchange error (which is not the case)
=> unauthorized user get ncclient hanging

ncclient/transport/third_party/junos/ioproc.py
+ alternating buffer write and read
+ assumtion that there is no response without request
+ improvement of up to 100ms per request for requests in quick succession
+ cpu friendly (blocking read/write wihtout timeout)
=> junos ioproc performance

examples/nc08.py
Example for IOS XR. 
Also, it creates a XML using lxml/etree instead of templates.
=> Example for IOS XR

examples/juniper/edit-config-jnpr-json.py, examples/juniper/get-configuration-jnpr.py, ncclient/operations/third_party/juniper/rpc.py, test/unit/operations/third_party/juniper/test_rpc.py
Adding support and examples for JSON encoding
=> [Junos] Add support for JSON encoding (load-configuration) w/ examples

ncclient/operations/rpc.py
=> minor string substitution fix

setup.py
Fix https://github.com/ncclient/ncclient/issues/160
=> Fix #160 force UTF-8 encoding when opening README

ncclient/devices/default.py, ncclient/devices/huawei.py, ncclient/manager.py, ncclient/operations/__init__.py, ncclient/operations/notify.py, ncclient/operations/subscribe.py, ncclient/transport/session.py, ncclient/transport/ssh.py, ncclient/xml_.py, test/unit/devices/test_default.py, test/unit/operations/test_subscribe.py, test/unit/transport/test_session.py, test/unit/transport/test_ssh.py
This PR adds the ability to create NETCONF notification subscriptions and retrieve notifications from a queue when they are received.
=> Add notification support

examples/juniper/get-interface-status.py
This python script gets the interface name and their operational status.
=> get-interface-status.py

ncclient/operations/third_party/iosxe/rpc.py
Hi Team
This is a fix for issue #212. I just removed an extra argument from `request()` in `SaveConfig` class.
I hope it works out.
Tetsu
=> Fix issue #212.

ncclient/transport/ssh.py
Hi Team,
This pull request fixes issue #214.  See the issue for details.
Thanks,
Michael
=> Fix issue #214

.gitignore, examples/alu/edit_config.py, examples/alu/get_config.py, ncclient/devices/alu.py, ncclient/operations/third_party/alu/rpc.py, ncclient/xml_.py
Enhance Alcatel-Lucent(Nokia) -device support.
Summary:
- Add operations for Alcatel-Lucent -devices
- get_configuration
- show_cli
- load_configuration
- Enhange AluDeviceHandler to support additional operations
- Simple examples
*NOTE:* This add better support for Nokia -routers which are using Alcatel-Lucent YANG -models. I am working on to add support for devices using Nokia YANG -models. There is so much differences so it might be reasonable to add new device handler for Nokia -devices.
=> Alu enhancements

ncclient/transport/ssh.py
=> Read ssh timeout from config file

ncclient/transport/ssh.py
When using ncclient with a non-standard SSH port, only entries in
known_hosts where the port has explicitly been set are checked. This
differs from openSSHs handling of host keys where an entry with just the
host name / ip is also checked if an entry without the port is not
present.
For example, with a known host of:
10.0.0.1 ecdsa-sha2-nistp256 <redacted>
I could still connect with ssh -p 830 10.0.0.1, but with ncclient I
would need:
[10.0.0.1]:830 ecdsa-sha2-nistp256 <redacted>
This patch checks for known host keys matching either 'host' or
'[host]:port', to match the behaviour of OpenSSH.
Fixes: 302
=> Allow host or [host]:port when checking host keys

ncclient/transport/third_party/junos/parser.py, test/unit/transport/test_parser.py
Fix a minor bug in https://github.com/ncclient/ncclient/pull/324
=> handle rpc-reply start tag with no filter_xml

ncclient/transport/ssh.py
Modifying the existing log level message for SSH connections to debug level and added a new info level log message.
=> Reduce logging at info level

ncclient/transport/third_party/junos/parser.py, test/unit/transport/rpc-reply/get-software-information-rfc.xml, test/unit/transport/test_parser.py
Juniper/Junos SAX parser was not handling rfc-compliant rpc xml.
=> handle nc:rpc tags

ncclient/transport/third_party/junos/parser.py
handle the case when rfc config is changed during a persistent connection
Removing class variable usage as it can impact other thread which might be using the connection to a different device
=> Sax parser rfc compliant

ncclient/capabilities.py, ncclient/devices/h3c.py, ncclient/manager.py, ncclient/operations/edit.py, ncclient/operations/rpc.py, ncclient/transport/session.py, ncclient/transport/third_party/junos/ioproc.py
Remove all the useless imports and some useless code
=> Remove useless imports and code

ncclient/devices/h3c.py
fixes issue#387.
change file annotation, Huawei to H3c
=> fix-issue#387 change file annotation

examples/ericsson_nc_prefix_example.py, ncclient/devices/ericsson.py, test/unit/devices/test_ericsson.py
Hi @einarnn ,
This PR fixes #344, please review it:-)
=> add a new interface to turnoff the namespace prefix nc

ncclient/xml_.py, test/unit/test_xml_.py
findall() method already presented in lxml, and i think the lack of this method in ncclient is not very convenient, so i added it
=> Add "findall" method to NCElement class

ncclient/transport/ssh.py, test/unit/test_manager.py
use like:
```
with manager.connect_ssh(host='host',
port='port',
username='user',
password='pswd',
hostkey_verify=False,
keepalive= 10) as m:
```
=> add connect parament - keepalive

.github/workflows/check.yaml, README.md
Update the icon displayed in README.md to reflect GitHub Actions test status.
=> Update Build Pill

examples/vendor/nokia/sros/config_mode.py
Hi @einarnn 
Thanks for approving my [PR](https://github.com/ncclient/ncclient/pull/594). 
I left some hardcoded values there. I removed them in this PR!
=> remove hardcoded values in example

ncclient/transport/libssh.py
This PR adressess issue #644.
- fix default value of allow_agent parameter
- add warning when using unsupported parameters
=> Fix connect() params of libssh transport
