ncclient/manager.py
If the user deliberately wants to ignore host verifications, loading the known_hosts (which takes a considerable time) is useless.
=> Specifying hostkey_verify=False should not load_known_hosts

ncclient/devices/default.py
Some devices don't send back error_text with an RPC error. This checks to see if error_text is None and if it is sets it to reflect the lack of message. Without this check you receive an 'AttributeError' for devices not containing error_text and no helpful output to troubleshoot the actual RPC error.
=> Add check for device sending back null error_text.

ncclient/manager.py
When using `raise ex`, the stack trace leading to the `ex` exception is
lost. For example, when trying to connect to a non-existant host, I get
this:
Traceback (most recent call last):
File "examples/nc01.py", line 21, in <module>
demo(sys.argv[1], os.getenv("USER"))
File "examples/nc01.py", line 16, in demo
with manager.connect(host=host, port=22, username=user) as m:
File "/home/bernat/code/exoscale/ncclient/ncclient/manager.py", line 147, in connect
return connect_ssh(*args, **kwds)
File "/home/bernat/code/exoscale/ncclient/ncclient/manager.py", line 120, in connect_ssh
raise ex
socket.gaierror: [Errno -2] Name or service not known
By just raising the original exception, the stacktrace is kept. For
example:
Traceback (most recent call last):
File "examples/nc01.py", line 21, in …
=> manager: on connect exception, keep stacktrace

ncclient/transport/ssh.py
Instead of specifying the path to `ssh_config`, a user can just use
`True` to use the default path.
=> ssh: enable `ssh_config=True` to default to `~/.ssh/config`

ncclient/operations/rpc.py
The RFC (https://tools.ietf.org/html/rfc6241#page-16) states that the error-type is of [transport, rpc, protocol, application] and error-severity is [error, warning] so when a request is in raise_mode "error" the code needs to check with the error-severity field instead of error-type.
Here is a new "example" modified as a test, which i test against a Juniper JunOS 11.4R1.6 :
#! /usr/bin/env python2.6 
#
#
import sys
import os
import warnings
warnings.simplefilter("ignore", DeprecationWarning)
from ncclient import manager
config = """<config><configuration><vlans><vlan><name>%s</name>
<description>%s</description></vlan></vlans></configuration></config>"""
def demo(host, user, vlan, new_desc):
with manager.connect(host=host, port=22, username=user, hostkey_verify=False) as m: …
=> Check the correct field on rpc-error element

.travis.yml, README.md
Quite a simple modification, as the tests already perform coverage
analysis.
I guess you'd have to create an account in https://coveralls.io/ to make this useful...
=> Add coveralls support, with shield in README.md

ncclient/devices/hpcomware.py, ncclient/operations/third_party/hpcomware/rpc.py
re: `ncclient/operations/third_party/hpcomware/rpc.py`
Added a custom operation to allow sending CLI commands to HP Comware devices
re: ncclient/devices/hpcomware.py
I have a question on the `get_xml_extra_prefix_kwargs`.  While what I have here works, after some testing, I can added totally bogus namespaces here, and they work, and are always returned in the netconf reply.  Would you mind providing a little more context to these k/v pairs?
Thanks.
=> Add support for HP Comware v7 devices

ncclient/xml_.py
Without encoded date python 3.x would break with:
ncclient/ncclient/xml_.py", line 104, in to_ele
return x if etree.iselement(x) else etree.fromstring(x, parser=parser)
File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:82934)
File "src/lxml/parser.pxi", line 1814, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:124471)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
=> encoding data otherwise getting exception ValueError

ncclient/devices/huawei.py
@leopoul good suggestion, it works :)
Besides, it would be better if we can avoid the 'try ... except' block in _dispatch_message(),
for example, change the handle_raw_dispatch() in devices/default.py:
```python
def handle_raw_dispatch(self, raw):
return raw
```
=> strip \0 in response for huawei

ncclient/operations/third_party/huawei/rpc.py
Fix two points for third party operation:
1. For huawei device, the action rpc's keyword is "execute-action".
2. For huawei private rpc operation, the namespace should use its private namespace string..
=> fix(third_party): huawei action operation keyword

ncclient/transport/ssh.py
10,000,000.
In _parse11(), current chunk size is compared with MAX_STARTCHUNK_SIZE which is currently set as 10 (10 digits for 4294967295).
However the chunk size line character is counted including the leading '#' and \'n' at the end of line so this makes it detects as chunk size too long with 8 digit chunk size.
Thus I simply increased MAX_STARTCHUNK_SIZE to 12.
=> Fixed a bug causing parse error when the reply message size exceeds 

ncclient/operations/retrieve.py
This correctly extracts the YANG model from the reply unlike the generic
GetReply class which uses the wrong namespace.
I've only tried this on an XR box so someone should try this on other devices before merging to make sure I haven't broken something.
=> Use specific reply class for GetSchema

ncclient/operations/edit.py, test/unit/operations/test_edit.py
The validate RPC is supposed to contain either a datastore name or a full configuration tree as the source (RFC 6241, 8.6.4.1). This change reflects that.
=> support for datastores and configuration in validate

ncclient/transport/ssh.py, test/unit/transport/test_ssh.py
Parsing :base:1.1 messages is broken under Python 3. This kind of change - converting between data type coming out of the SSH channel and expected by the XML parser - has been done before for :base:1.0 framing, but was missing for 1.1.
The change also adds new unit test exactly for 1.1 parsing.
=> Python 3 support for 1.1 message chunked framing

ncclient/transport/ssh.py, test/unit/transport/test_ssh.py
When receiving a 4096 bytes message ending with ']]>]]', the remaining '>' is
prepend to the next message parsed.
This patch asserts that the delimiter ']]>]]>' is complete before parsing the
message, avoiding to prepend the next message with invalid characters.
=> Fix receiving an incomplete delimiter in netconf ssh transport

ncclient/devices/iosxe.py
simple fix to at least connect to iosxe devices.
=> fix for iosxe connection

ncclient/devices/iosxr.py, ncclient/operations/third_party/iosxr/rpc.py, ncclient/transport/ssh.py, ncclient/transport/third_party/iosxr/ioproc.py, ncclient/xml_.py
Currently the support for Cisco IOS-XR devices is not very well covered. However, they seem to have implemented properly most of the standard format requests.
The namespace changes in ```get_xml_extra_prefix_kwargs``` and ```get_xml_base_namespace_dict``` are important - the device does not seem to like qualified tags and even a hello message will fail if the RPC tag is formatted as ```<nc:hello>```, or ```<nc:rpc>```.
Basic functions such as ```lock```, ```unlock```, ```discard_changes``` etc can be issued using the default requests. I've added also support for executing arbitrary RPC requests and ```get``` or ```get_config``` with or without filter for ease of use (e.g.: ```conn.get()``` or ```conn.get(filter='<interface-configurations …
```
=> Augmenting IOS-XR support

examples/nxosapi.py
Use the 'nexus' device profile since it's a Nexus we are dealing with. I
don't see how this every worked without it, at least it doesn't for me
on a Nexus 3048.
A bunch of the XML was simply incorrect, like the closing switchport tag
that was missing a leading /. There was an empty
'<switchport></switchport>' which obviously adds nothing.
The enable/disable vlan on a port functions are modified to add and
remove the VLAN instead of trying to replace the entire list of allowed
VLANs. The disable function was previously not working at all as it
tried to write the VLAN to <notallowed> which simply doesn't exist.
=> Fix example for Nexus

ncclient/transport/ssh.py, requirements.txt, test/unit/transport/test_ssh.py
These keys are supported in paramiko 1.15.0 and higher via #218
https://github.com/paramiko/paramiko/pull/218
=> Add support for ECDSA private keys.

examples/juniper/execute-async-rpc.py
This script connects to a Juniper device and issues an asynchronous rpc request for get-software-information, then waits for the action to complete and prints out the hostname. 
Contrary to a synchronous rpc call [execute-rpc.py](https://github.com/ncclient/ncclient/blob/master/examples/juniper/execute-rpc.py), more work is required to parse the reply.
=> juniper async rpc example

examples/juniper/outbound-ssh-ncclient.py, ncclient/transport/ssh.py, test/unit/test_manager.py
Cherry-pick open pull request #67, which allows the use of an already open socket for the ssh connection via ssh, but use a socket file descriptor instead of the socket object in order to pass it as number between processes. 
This change is required for PyEz and SaltStack Proxy to support Junos outbound ssh by running a salt-proxy daemon on a given TCP port and fork per incoming connection based on DEVICE-ID.
Example script with required Junos configuration can be found in [examples/juniper/outbound-ssh-ncclient.py](https://github.com/mwiget/ncclient/blob/outbound-ssh/examples/juniper/outbound-ssh-ncclient.py).
Related PyEz and SaltStack "work-in-progress" changes can be found in 
[https://github.com/mwiget/py-junos-eznc/tree/outbound-ssh](https://github.com/mwiget/py-junos-eznc/tree/outbo …
=> Juniper outbound-ssh support

ncclient/xml_.py, test/unit/operations/test_utils.py, test/unit/operations/third_party/juniper/test_rpc.py, test/unit/transport/test_session.py
This option was added via commit 858a13acd16043d1682f469a6274befe618a1d2b back in 2014.  This means that clients must do full validation of content prior to calling ncclient.
This option is dangerous and can result in broken XML being silently discarded with unintended consequences (consider options to an RPC call that were meant to be specific that may have been invalid).  The end result is some XML could still pass and be constructed.
If this was necessary to deal with broken XML then it should be fixed at the endpoint and not reside in core infra.
=> Remove dangerous 'recover=True' option from XMLParser

ncclient/devices/csr.py, ncclient/devices/iosxe.py, ncclient/operations/rpc.py
Fixes issue #205 . A bad indented "else" was causing an issue with RPC's that did not have the "message-id" attribute. This fix removes that code and reworks the logic of handling the attributes.
=> Fix incorrect handling of RPC

ncclient/devices/default.py, ncclient/operations/retrieve.py, ncclient/xml_.py, test/unit/devices/test_default.py, test/unit/operations/test_retrieve.py, test/unit/transport/test_ssh.py
RFC 6243 defines an optional "with-defaults" parameter for "get" and "get-config" requests that determines how a NETCONF server should handle retrieving default configuration values. This update adds support for this parameter.
- Added "with-defaults" support to Get and GetConfig
- Added the "with-defaults" capability to the default client
- Wrote tests for all of the new cases
=> Added "with-defaults" capability for "get" and "get-config" requests

examples/juniper/rollback.py, ncclient/devices/junos.py, ncclient/operations/third_party/juniper/rpc.py, test/unit/devices/test_junos.py
Add support for JUNOS rollback configuration by adding
new `rollback` API.
=> Add rollback api for junos device

docs/source/operations.rst, ncclient/manager.py, ncclient/operations/__init__.py, test/unit/operations/test_edit.py
The RPC itself has already been implemented, it just wasn't attached
to the manager object.
=> Add cancel_commit to the manager

README, README.md, README.rst, examples/nc01.py, examples/nc02.py, examples/nc03.py, examples/nc04.py, examples/nc05.py, examples/nc06.py, examples/nc07.py, examples/nc08.py, examples/nxosapi.py, ncclient/__init__.py, setup.py
Fixes #228.
Also add `python_requires` to setup.py to help pip, and assume Python 3.4 is the min Python 3.x supported, as this is the lowest tested by Travis CI. It's also the lowest still supported CPython version.
=> Drop support for Python 2.6

ncclient/operations/edit.py, test/unit/operations/test_edit.py
Make CopyConfig.request accept source with <config> element
containing the configuration subtree to copy.
=> Add support for embedding <config> in copy-config

ncclient/operations/third_party/juniper/rpc.py, test/unit/operations/third_party/juniper/test_rpc.py
Fixes #238
*  As per Juniper documentation the correct xml tag for commit rpc
is `commit-configuration` and not `commit`.
*  Add support for `check` mode
Before in case commit is not issued after confirm commit.
Device logs show rollback happens immediately
```
user@junos# show | compare rollback ?
Possible completions:
0                    2018-06-14 04:59:12 UTC by junos via netconf
1                    2018-06-14 04:59:07 UTC by junos via netconf commit confirmed, rollback in 0mins
```
After the patch in this PR is applied
```
[edit]
Broadcast Message from user@junos
(no tty) at 5:41 UTC...
Commit was not confirmed; automatic rollback complete.
user@junos# show | compare rollback ?
Possible completions:
0                    2018-06-14 05:41:40 UTC by root via other
1 …
```
=> Fix junos confirm-commit issue and check mode issue

ncclient/operations/third_party/juniper/rpc.py, test/unit/operations/third_party/juniper/test_rpc.py
Based on @ganeshrn fix (https://github.com/ncclient/ncclient/pull/239), but also clear the namespace for commit-configuration element (https://www.juniper.net/documentation/en_US/junos/topics/reference/tag-summary/junos-xml-protocol-commit-configuration.html) and update the corresponding unit tests.
I also tested it with a real Juniper SRX 300.
=> Fix junos confirm-commit issue (improved version)

examples/juniper/command-jnpr.py, examples/juniper/compare-config-jnpr.py, examples/juniper/delete-config-jnpr.py, examples/juniper/edit-config-bgp-peer.py, examples/juniper/edit-config-jnpr-json.py, examples/juniper/edit-config-jnpr-set.py, examples/juniper/edit-config-jnpr-text.py, examples/juniper/edit-config-jnpr.py, examples/juniper/edit-config-std.py, examples/juniper/edit-config-text-std.py, examples/juniper/execute-async-rpc.py, examples/juniper/execute-rpc-string.py, examples/juniper/execute-rpc.py, examples/juniper/get-config-jnpr.py, examples/juniper/get-configuration-jnpr.py, examples/juniper/get-configuration-matching.py, examples/juniper/get-interface-status.py, examples/juniper/get-inventory.py, examples/juniper/get-session-params.py, examples/juniper/get-xnm-information.py, examples/juniper/get_l2vpns.py, examples/juniper/outbound-ssh-ncclient.py, examples/juniper/pubkey-auth.py, examples/juniper/request-reboot.py, examples/juniper/rollback.py, examples/juniper/set-description.py, examples/juniper/unknown-rpc.py
- Old, python 2 style print statements replaced with logging.info() (logging configured to show date, python file name and line number),
- Using bigger timeout values for manager.connect(), needed by e.g. Juniper SRX 300 (which I could test with) for some operations,
- More meaningful, less confusing/misleading/sloppy variable names,
- get-configuration-jnpr.py: fix: the result of get_configuration() used a bit different data structure,
- get-xnm-information.py: XML (NCElement) to str conversion fix for python 3,
- Some/most PEP 8 code formatting issues were fixed (what I noticed in PyCharm),
- Unnecessary user input (raw_input()) removed from the examples where it was present, easier to run them this way (especially multiple times),
- Note: some examples may still be broken, did not have …
=> examples/juniper various improvements (issue #236 plus more):

ncclient/manager.py, test/unit/test_manager.py
Allow a custom device handler to be supplied to the manager via the
device_params dictionary.
=> Add support for custom device handlers

setup.py
Put in checks to disable installation with Python 3.7 due to current use of `async` for parameters, as `async` has been added as a keyword to Python 3.7.
=> Merge preparing for 0.5.4 release

.travis.yml, README.md, README.rst, ncclient/manager.py, ncclient/operations/rpc.py, setup.py, test/unit/operations/test_rpc.py
Requires changing `async` to non-keyword value. Chose to use `async_mode`.
=> Updates to re-enable Python 3.7

ncclient/devices/huaweiyang.py
The existing huawei.py device having some private capabilities in <hello>, like "http://www.huawei.com/netconf/capability/exchange/1.0", which tell the connected NE (network element) to work in private work-mode. 
In order to ask NE to work in  standard way that accpeting only RFC compatible rpc and reply with standard rpc-reply, huaweiyang.py is added
=> add Huawei device support through YANG

README.md, ncclient/transport/session.py, ncclient/transport/ssh.py, requirements.txt, test/unit/transport/test_ssh.py
Change from using the current `select.select` to test for file descriptor (socket/channel) activity to using `selectors.DefaultSelector` or `selectors2.DefaultSelector` on Python 2.7. The concrete selctor are the `KqueueSelector` on macOS and the `EpollSelector` on linux (Ubuntu 16.0.4) for both Python 2.7 and Python 3.7.
=> Move from use of select.select to selectors.DefaultSelector

ncclient/transport/session.py, ncclient/transport/ssh.py, requirements.txt, test/unit/transport/test_ssh.py
Change from using the current `select.select` to test for file descriptor (socket/channel) activity to using `selectors.DefaultSelector` or `selectors2.DefaultSelector` on Python 2.7. The concrete selctor are the `KqueueSelector` on macOS and the `EpollSelector` on linux (Ubuntu 16.0.4) for both Python 2.7 and Python 3.7.
=> selector changes

ncclient/logging_.py, ncclient/operations/rpc.py, ncclient/transport/session.py, ncclient/transport/ssh.py, test/unit/transport/test_session.py
Something of a continuation of #263. For session-related logs, use a LoggingAdapter to automatically include the session information as context in the log record. This allows end users as well as API consumers of ncclient to filter log messages appropriately in the case where multiple sessions are coexisting.
Example output:
```
ncclient.transport.session: DEBUG: [session 0x10be336d8] <Session(session, initial daemon)> created: client_capabilities=[':candidate']
ncclient.transport.session: DEBUG: [session-id 100] installing listener <ncclient.transport.session.NotificationHandler object at 0x10be26eb8>
ncclient.transport.session: DEBUG: [session-id 100] installing listener <ncclient.transport.session.HelloHandler object at 0x10be26ef0>
ncclient.transport.session: DEBUG: [session-id 100] …
```
=> Add session as extra context to session-related logs

ncclient/xml_.py
a user can pass transform reply as function. So with this, users' can use their own logic to transform the xml. 
With this functionality, I am not bound to use xslt for transformation. For a 24000 IFL configuration (100mb data) took 45 sec to parse. With our own remove_namespace logic it takes 8 seconds only. We also see these benefits 
  | Old Code | New Code | Improvement
-- | -- | -- | --
CPU | 1.8GB | 850 MB | > 50%
Time Taken | 140 sec | 95 sec | > 30%
Example of how to use this feature
https://github.com/vnitinv/py-junos-eznc/commit/43f79262a84f01c9acbaf407d3a7f4c2a6a631c1
=> check for transform_reply type

ncclient/transport/ssh.py
I had an error when opening and closing SSH sessions to several hundreds of devices because of too many file descriptors opened.
Close all file descriptors that have been opened by the channel, fixing the issue.
=> Close the channel when closing SSH session

requirements.txt
Pin the "selectors2" package to Python versions lower/equal than 3.4 . Otherwise packages, that depends on ncclient, e.g. napalm will fail at runtime when used with Python 3.6 or later.
This should fix #291
=> Pin selectors2 to Python versions <= 3.4

examples/nc04.py, examples/nc05.py, examples/nc06.py, examples/nc07.py, examples/nxosapi.py
In the examples, the <config> node wasn't actually using the prefix.
If an XML node uses no XML namespace, it defaults to the ancestor
default. In ncclient, the root <rpc> node has no default namespace, only
`nc` which maps to `urn:ietf:params:xml:ns:netconf:base:1.0`.
Pedantic NETCONF servers were rejecting the RPCs, since the <config>
element was not in the correct namespace.
I also changed the `xc` namespace prefix, to match with one defined in the
ancestor `<rpc>` node.
=> Fix config examples to actually use the `nc` namespace.

ncclient/transport/ssh.py, test/unit/ssh_config, test/unit/test_manager.py
In order to use a jumphost to communicate with a network device, you need to set the ProxyCommand in your ssh_config file to specify the jumphost to connect to.
For example, if you are trying to connect to 10.0.0.1 via jumphost.domain.com you need the following in your ssh_config
```
Host 10.0.0.1
hostname 10.0.0.1
proxycommand ssh -W %h:%p jumphost.domain.com
```
When you attempt to connect to 10.0.0.1 %h and %p are replaced with the target host and the target port number respectively.
When using ncclient and using this strategy the replacement of %p is replaced with the default port in paramiko (22) rather than the port you have specified in manager.connect()
As a result you are connected to port 22 regardless of what port number is passed into manager.connect.
This pull request fixes …
=> Correctly set port number in in ProxyCommand when using ssh_config file

ncclient/operations/third_party/juniper/rpc.py, test/unit/operations/third_party/juniper/test_rpc.py
This change allows you to specify the format for comparison between configrations.
Text seems to be the implicit default for any value of rollback other than the default (0) so it is a good choice and will result in uniform output i.e. you can rely on there being a `configuration-output` element if there is a difference.
=> Juniper RPC: allow specifying format in CompareConfiguration

ncclient/operations/util.py
As per RFC5277 page 29, "filter" in "create-subscription" is in namespace "urn:ietf:params:xml:ns:netconf:notification:1.0". However, in RFC6241 page 27, "filter" in "get-config" is in namespace "urn:ietf:params:xml:ns:netconf:base:1.0".
The issue is create_subscription() returns error with correct filter:
>>> filter = """
... <filter xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0"
...         xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
...         nc:type="subtree">
...   <foo xmlns="urn:params:xml:ns:yang:foo">
...   </foo>
... </filter>"""
>>> reply = nc.create_subscription(filter=filter)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/jonyang/Projects/unclean/ncdiff/src/ncdiff/manager.py", line 343, in execute
reply = …
=> Fix filter in create_subscription in issue#224

ncclient/transport/ssh.py
Parsing of NETCONF 1.1 frames no longer decodes each chunk of bytes to unicode. This was causing a massive performance hit when retrieving a large config.
=> Improved NETCONF 1.1 message parsing efficiency

ncclient/capabilities.py, ncclient/operations/retrieve.py, test/unit/operations/test_retrieve.py
Summary of changes:
- Represent capabilities as objects with separate namespace URI and parameters
- Provide an interface for accessing individual capabilities in order to check these parameters
- Validate the `with-defaults` mode using the modes advertised by the server via the parameters in the capability URI
=> Validate 'with-defaults' mode based on supported modes advertised in capability URI

ncclient/manager.py, ncclient/transport/ssh.py, test/unit/test_manager.py
Fixes #313 
The timeout kwd parameter of manager.connect_ssh ended up being used for two rather contradicting purposes:
* It is passed as a kwd to transport.SSHSession.connect , where it serves as a connection timeout. This matches the documentation of the manager.connect_ssh function
* It is also passed as kwd to manager.Manager(), where it serves as synchronous RPC timeout
This pull request addresses this issue by making sure that the factory method kwd arguments contain only arguments for transport.SSHSession.connect , and any argument for the Manager constructor is passed in a "manager_parameters" dictionary.
=> Correctly dispatch different timeout paramters for ssh connect and RPC timeout

docs/source/manager.rst, docs/source/operations.rst, ncclient/manager.py, ncclient/operations/rpc.py, ncclient/operations/third_party/juniper/rpc.py, ncclient/xml_.py, test/unit/operations/test_rpc.py, test/unit/operations/third_party/juniper/test_rpc.py, test/unit/test_manager.py
Fixes #185 
This merge request adds a `huge_tree` paramater for the "Manager", which can be tweaked in multiple places:
* global level `manager.Manager.HUGE_TREE_DEFAULT`, in case the library is used by another library that cannot be modfied
* as a property for the `Manager` (the solution suggested in #186)
* at the RPC implementation level (e.g. `third_party.juniper.rpc.GetConfiguration` enables huge_tree support for non-xml configuration formats)
Note, that at least for lxml for Python 3.6, the xml parsing of `huge text node` is not triggered for huge text nodes that do not contain XML escaped characters (e.g. `&gt;` for `>`).
=> Add option to parse XML replies with huge text node (fixes #185)

.gitignore, MANIFEST.in, setup.cfg, setup.py, test-requirements.txt, tox.ini
This patch adds tox support to the project for running pep8,
documentation building and testing against py27 and py3.
The pep8 tests fail due to various actual pep8 violations, but at least
this patch allows one to run the pep8 tests.
=> Add tox support

docs/source/transport.rst, ncclient/transport/ssh.py
If the client device has multiple IP interfaces, in some cases the SSH connect attempts to use a local address that can’t be reached by the remote host. This results in failure to establish an SSH connection.
The fix is trivial: allow the caller to optionally pass a source address when connecting to the netconf host. This, in turn, is used in the socket.bind().
=> Allow source address for SSH connection

ncclient/transport/third_party/junos/ioproc.py
* Junos specific changes
Use subprocess `communicate` in place of a `wait` so that there is a clean up of buffer and it closes the process connection.
=> fix: "Too many open files" for Junos devices 

ncclient/operations/edit.py, test/unit/operations/test_edit.py
NETCONF edit-config expects default-operation first and then test and
error option, otherwise libnetconf2 throws below error.
"Invalid order of elements "default-operation" and "error-option".
(/ietf-netconf:edit-config/default-operation)"
the order as per ietf-netconf.yang is
- default_operation
- test_option
- error_option
=> Fix the order of operations in edit-config

ncclient/manager.py
Fixes #325
*  If the rpc response timeout value is not passed in
`manager_params` dictionary fallback on the `timeout`
value passed to `connect` API to manitain backward
compatibility.
Reproducer script: https://gist.github.com/ganeshrn/051f849fb1dddaafc854ab79ebfda598
=> Allow setting manager timeout with backward compatibility

ncclient/transport/third_party/junos/parser.py
`remaining` is a string whereas sax parser expects bytes
=> Junos sax parser

ncclient/operations/subscribe.py, test/unit/operations/test_subscribe.py
The original namespace used for sub tags are different from the create-subscription, which is currently rejected by NSO5.2.x.
As responds from NSO team:
(1) Messgae format accpted by NCS 4.7.x
```
<nc:rpc message-id="urn:uuid:bfc416da-1265-44b5-87aa-734fc7b4cd96"
xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
<ns0:create-subscription xmlns:ns0="urn:ietf:params:xml:ns:netconf:notification:1.0">
<nc:stream>NETCONF</nc:stream>
<nc:startTime>2019-09-26T13:57:07+00:00</nc:startTime>
</ns0:create-subscription>
</nc:rpc>
```
(2) Message format accepted by NCS 4.7.x and NCS 5.x
```
<nc:rpc message-id="urn:uuid:bfc416da-1265-44b5-87aa-734fc7b4cd96"
xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
<ns0:create-subscription xmlns:ns0="urn:ietf:params:xml:ns:netconf:notification:1.0"> …
```
=> Use same namespace for create-subscription and sub tags

ncclient/devices/huaweiyang.py
Add `urn:ietf:params:netconf:base:1.1` -capability to huaweiyang -device handler.
This allow's usage of Netconf 1.1 -features(eg. remove -operation) against Huawei devices with latest SW.
=> Add base:1.1 capability to huaweiyang -device handler

ncclient/operations/edit.py
Added support for persist-id element as discussed in the https://github.com/ncclient/ncclient/issues/357
=> added support for persist-id element in the commit RPC

ncclient/transport/session.py
Fix #364
Before fix
we don't need to put debug for different listeners. It unnecessarily put same log message for different listener multiple times.
In case of huge XML output, logging becomes clumsy 
```
DEBUG:ncclient.transport.ssh:[host 10.221.130.141 session-id 51814] dispatching message to <ncclient.transport.session.NotificationHandler object at 0x108c162e8>: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/19.3R0/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:c8fefa58-5cc8-478e-8e60-e340b9409c1a">
....
</rpc-reply>
DEBUG:ncclient.transport.ssh:[host 10.221.130.141 session-id 51814] dispatching message to <ncclient.operations.rpc.RPCReplyListener object at 0x1086fa588>: <rpc-reply …
```
=> cleanup logging

ncclient/transport/ssh.py
In case of failed known_host verification attempt of raising SSHUnknownHostError was performed. Problem was that for SSHUnknownHostError object creation "known_hosts_lookup" variable was used in the code but this variable doesn't exist (typo - proper name: "known_hosts_lookups"). Result was strange NameError and time spent on investigation ;)
=> NameError instead of SSHUnknownHostError in case of failed known_hosts verification - bugfix

ncclient/transport/ssh.py
This code relies on the internal mapping class in Paramiko, but the variable might hold a normal Python dictionary due to the previous lines, so it crashes when `self._host_keys.lookup(host_port)` is true. The keys to this virtual dictionary are already "x.key.get_name()", so it can be simplified to iterating over it.
=> Fix error due to use of private paramiko class attribute

ncclient/operations/edit.py
From the following in section 8.4 of the RFC - https://tools.ietf.org/html/rfc6241#section-8.4 -
```
A confirmed <commit> operation MUST be reverted if a confirming
commit is not issued within the timeout period (by default 600
seconds = 10 minutes).  The confirming commit is a <commit> operation
without the <confirmed> parameter.  The timeout period can be
adjusted with the <confirm-timeout> parameter.  If a follow-up
confirmed <commit> operation is issued before the timer expires, the
timer is reset to the new value (600 seconds by default).  Both the
confirming commit and a follow-up confirmed <commit> operation MAY
introduce additional changes to the configuration.
If the <persist> element is not given in the confirmed commit
operation, any follow-up commit and the confirming commit …
```
=> Allow for follow-up confirmed commit with persist-id

ncclient/manager.py
Updates for:
https://github.com/ncclient/ncclient/issues/386
This moves the vendor operations functionality into the created instance and removes the global variable. My org was running into instances where we use the same celery worker process to work on multiple vendors, and even while not using threads this is an issue for us.
=> global variable fix

ncclient/xml_.py, test/unit/test_xml_.py
This PR resolves the second of issue #176. it means let sub_ele inherit parent namespace per default
=> Bugfix #176 sub_ele should inherit parent namespace

docs/requirements.txt
The documentation over at https://ncclient.readthedocs.io/en/latest/ is missing a lot of information. Mostly this seems to be caused by lxml not being installed in the RTD build process causing a lot of errors
```
WARNING: autodoc: failed to import class 'operations.RPC' from module 'ncclient'; the following exception was raised:
No module named 'lxml'
WARNING: autodoc: failed to import class 'operations.RPCReply' from module 'ncclient'; the following exception was raised:
No module named 'lxml'
WARNING: autodoc: failed to import exception 'operations.RPCError' from module 'ncclient'; the following exception was raised:
No module named 'lxml'
WARNING: autodoc: failed to import class 'operations.Get' from module 'ncclient'; the following exception was raised:
No module named 'lxml' …
```
=> Add missing requirements to fix broken RTD builds

ncclient/operations/edit.py, ncclient/operations/util.py, test/unit/operations/test_edit.py
Hi, 
This PR adds a `url` option to `edit-config`, as mentioned at #431. :-)
=> Bugfix url option is missing for edit-config

ncclient/manager.py, ncclient/operations/__init__.py, ncclient/operations/retrieve.py, ncclient/operations/rpc.py, test/unit/operations/test_rpc.py, test/unit/test_manager.py
@einarnn Hi,
I found some unreasonable places in Dispatch as follows.
1. Dispatch RPC uses `GetReply` for its reply class, as you mentioned at #252.
2. It doesn't support the operations w/ `config` or `target` parameter, such as `edit-config`, `copy-config` and so on.
This PR fixes them. :-)
=> Bugfix some unreasonable places in Dispatch

ncclient/transport/__init__.py, ncclient/transport/ssh.py, test/unit/transport/test_ssh.py
The 1.1 chunking implementation is broken for multibyte characters - the implementation counts number of characters, but it should count number of bytes.
=> Fixed support for 1.1 chunking with multibyte characters

ncclient/operations/session.py
I deeply studied the infinite loop problem and found that it might be caused by the `close-session` operation.
1.  the first example:
```
conn = manager.connect(...)
a = conn.close_session()
print(a)
```
the result:
```
<rpc-reply xmlns=“xxx”, message-id="xxx"><ok/></rpc-reply>
```
2. the second example like https://github.com/ncclient/ncclient/issues/394#issuecomment-639332018
```
#!/usr/bin/env python3
import threading
from ncclient import manager
class test(object):
def __init__(self):
self.client = manager.connect(
host="xxx",
port=xxx,,
username="admin",
password="admin",
hostkey_verify=False,
look_for_keys=False,
allow_agent=False,
)
raise Exception()
def __del__(self):
print(threading.current_thread())
print(threading.currentThread())
print("close",flush=True) …
```
=> Refactor the close-session request in order to avoid deadloop

ncclient/manager.py, ncclient/transport/ssh.py, test/unit/test_manager.py
code like:
#!/usr/bin/env python
from ncclient import manager
if __name__ == '__main__':
with manager.call_home(host='', port=4334, username='netconf', password='netconf', hostkey_verify=False) as m:
c = m.get_config(source='running').data_xml
=> add support for call home feature

ncclient/devices/default.py, ncclient/devices/junos.py, ncclient/operations/rpc.py, ncclient/xml_.py, test/unit/operations/test_rpc.py
Fixes #276
This is a workaround for the fact that the juniper reply to the get-schema rpc has the wrong namespace for the <data> element:
- with the default settings `<data>` has namespace "urn:ietf:params:xml:ns:netconf:base:1.0"
```
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/19.1R0/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:71541af6-87e8-4f34-b1d8-3ec43dac6d38"> 
<data> 
```
- after applying 'set system services netconf rfc-compliant' `<data>` has no namespace whatsoever (probably a bug, because a ncm prefix is defined, in the data element, but the data element itself is not prefixed).
```
<nc:rpc-reply xmlns:junos="http://xml.juniper.net/junos/19.1R0/junos" …
```
=> Junos get schema workaround

ncclient/operations/third_party/h3c/__init__.py, ncclient/operations/third_party/h3c/rpc.py, ncclient/operations/third_party/huawei/__init__.py, ncclient/operations/third_party/huawei/rpc.py
Remove shebang (#!) lines from Python sources that are not intended to be executed as scripts.
=> Remove shebang (#!) lines from non-script Python sources

ncclient/transport/third_party/junos/ioproc.py
subprocess.check_output() in python3 return bytes instead of string as in python2, so line 46 raise an exception "TypeError: cannot use a string pattern on a bytes-like object"
Decoding stdoutdata as "latin-1" prevents it. Also in this case six.b() does not need any more
=> fix junos ioproc connection in python3

test-requirements.txt, test/unit/devices/test_junos.py, test/unit/operations/test_edit.py, test/unit/operations/test_lock.py, test/unit/operations/test_retrieve.py, test/unit/operations/test_rpc.py, test/unit/operations/test_session.py, test/unit/operations/test_subscribe.py, test/unit/operations/test_utils.py, test/unit/operations/third_party/alu/test_rpc.py, test/unit/operations/third_party/h3c/test_rpc.py, test/unit/operations/third_party/hpcomware/test_rpc.py, test/unit/operations/third_party/huawei/test_rpc.py, test/unit/operations/third_party/iosxe/test_rpc.py, test/unit/operations/third_party/juniper/test_rpc.py, test/unit/operations/third_party/nexus/test_rpc.py, test/unit/operations/third_party/sros/test_rpc.py, test/unit/test_manager.py, test/unit/transport/test_parser.py, test/unit/transport/test_session.py, test/unit/transport/test_ssh.py
See also https://fedoraproject.org/wiki/Changes/DeprecatePythonMock.
=> Use unittest.mock from the Python 3 standard library instead of PyPI mock, when available

test/unit/test_xml_.py
The nose package is dead upstream (https://nose.readthedocs.io/en/latest/, https://github.com/nose-devs/nose/commits/master).
This PR removes the hard dependency on `nose` in the actual test code, while leaving it in `test-requirements.txt` and the recommended testing command line in `README.md`. This change allows downstream users and packagers to run the tests without requiring `nose`.
See also https://fedoraproject.org/wiki/Changes/DeprecateNose.
=> Do not import nose in the tests; allows testing without nose

ncclient/manager.py
Addressing #488 to revert unintentional change of behavior for RPC lookup.
=> remove explicit rpc method and revert to getattr path

ncclient/devices/csr.py, ncclient/devices/default.py, ncclient/devices/iosxe.py, ncclient/operations/edit.py, test/unit/devices/test_iosxe.py
If a caller providing XML content to an IOS XE device (using `IosxeDeviceHandler`) accidentally omits the base netconf namespace from an `edit-config` request, the `IosxeDeviceHandler` will now automatically add the namespace to the `config` element.
=> add netconf base namespace to edit-config config element if it is missing

ncclient/manager.py, ncclient/transport/ssh.py, test/unit/test_manager.py, test/unit/transport/test_ssh.py
The SSH config option `UserKnownHostsFile`, if set, replaces the default - i.e. either `~/.ssh/known_hosts` should be used, or the file given by the config option, not both; using both might cause bogus `SSHUnknownHostError` exceptions. For this reason, the method `load_known_hosts` should be called only when the value of the option is known.
=> reading correct user known_hosts files

.github/workflows/check.yaml
Change the github action so that coverage is properly reported to coveralls.io; unfortunately it means removing python 2.7 testing, it does not appear to be supported by coveralls-python.
=> fix coveralls reporting

ncclient/transport/ssh.py
OpenSSH restricts the number of authentication retries to 6 i.e. You have 6 attempts in total to login to a remote system within a single TCP connection. This normally isn't a problem when authenticating with passwords or with private key files. A problem does exist when you attempt to authenticate using keys stored in the ssh-agent when the total key count is greater than 6 [ and private key file authentication is not enabled - in which case the number is reduced based on the number of key files specificed ( assuming that these authentications fail ) ] , currently there is no mechanism to select a specific key from the agent.
The merge request offers a simple solution to this problem that doesn't require significant changes to the existing code base - and will work silently with upstream …
=> Agent key selection

ncclient/transport/session.py
https://github.com/ncclient/ncclient/issues/542
Removing hardcoded timeout variable and replacing with a default parameter. This shouldn't affect any existing scripts as it will function the same when no parameter is passed.
=> Update session.py - Parameterize timeout for _post_connect

ncclient/transport/parser.py
Here is a modification suggestion for a comment that seems to contain a typo.
The comment refers to the regex pattern defined [here](https://github.com/ncclient/ncclient/blob/master/ncclient/transport/parser.py#L62):
```
RE_NC11_DELIM = re.compile(r'\n(?:#([0-9]+)|(##))\n')
```
The chunk delimiter, which contains digits, is matched by `group(1)`. `group(2)` is for the end delimiter, which doesn't contain any digits.
So the comment should mention `group(1)` instead of `group(2)`.
=> update comment in _parse11

ncclient/transport/session.py, ncclient/transport/ssh.py
Addressing https://github.com/ncclient/ncclient/issues/542
Extending https://github.com/ncclient/ncclient/pull/543 in conjunction with https://github.com/CiscoTestAutomation/yang/pull/69
Issue was discovered during the use of yang.connector to connect to a device using netconf, and running into timeout errors. The timeout was not being passed to the connection in ssh.py, and there was no ability to specify a custom timeout in session.py
=> Fix missing timeout in ssh post_connect

examples/vendor/nokia/sros/commit.py, ncclient/devices/sros.py, ncclient/operations/third_party/sros/rpc.py, test/unit/devices/test_sros.py, test/unit/operations/third_party/sros/test_rpc.py
This PR introduces the capability to include a comment when executing the commit RPC on SROS devices.
**Changes:**
1. Enhanced the SROS device handler to support the new `Commit` RPC class for `ncclient.operations.third_party.sros.rpc`.
2. Modified the `Commit` class to include a `comment` parameter that allows users to add a descriptive comment while committing configurations.
3. Added unit tests to ensure the correct behavior of the new commit `comment` functionality.
4. Added an example of its usage in the Nokia folder 
**Reason for Change:**
The SROS devices provide a way to include a descriptive comment while committing changes. This PR enables the ncclient users to leverage this feature. The comment can be beneficial for logging, audit purposes, or just to include descriptive notes …
=> Add commit comment capability support for SROS devices in ncclient

README.md, README.rst, docs/source/index.rst, ncclient/devices/__init__.py, ncclient/devices/ciena.py, test/unit/devices/test_ciena.py, test/unit/devices/test_get_supported_devices.py
=> Add Ciena driver

ncclient/manager.py
Sorry for the big delay. I have added this simple change to solve #557. By default and for backwards compatibility, it uses the same timeout there was before if nothing is specified in `kwargs`.
=> call_home: timeout as argument (#557)

README.md, examples/base/nc10.py, ncclient/manager.py, ncclient/transport/__init__.py, ncclient/transport/errors.py, ncclient/transport/unixSocket.py, test/unit/transport/test_UnixSocket.py
Added Unix Socket transport for local communication between ncclient and server.
```
unixSocketconnection = manager.connect_UnixSocket('path to socket', timeout)
```
Enables fast connections between ncclient and local servers and applications such as [clixon](https://github.com/clicon/clixon)'s backend server that uses unix socket rather than ssh.
(I also edited the readme 'for developers' section so that it now says to use pytest rather than nose for testing, #590)
=> Introduce Unix Socket Transport

examples/vendor/nokia/sros/config_mode.py, ncclient/devices/sros.py, test/unit/devices/test_sros.py
**Changes:**
- Enhanced `SrosDeviceHandler` to support "private candidate" mode:
- Added `urn:nokia.com:nc:pc` client capability when operating in private mode
- Introduced `config_mode` device parameter to switch between default and private modes
- Updated `get_capabilities()` to dynamically include private candidate capability
- Added unit tests to validate the behavior of private candidate mode and ensure correct NETCONF session handling
**Reason for Change:**
Nokia SR OS supports "private candidate" mode, allowing multiple concurrent NETCONF sessions to configure different parts of the device without locking conflicts. This is crucial for environments with simultaneous configuration changes, as it prevents locking errors.
We’ve experienced issues with concurrent NETCONF sessions …
=> feat: Add support for Nokia SR OS private candidate mode

ncclient/transport/ssh.py, test/unit/transport/test_ssh.py
ncclient directly tries to [load SSH private keys depending on their type](https://github.com/ncclient/ncclient/blob/652ef67b266df0ee02bbbbc4cc6eb09ca01f4878/ncclient/transport/ssh.py#L408-L419), circumventing Paramiko's [SSH certificate detection](https://github.com/paramiko/paramiko/blob/23f92003898b060df0e2b8b1d889455264e63a3e/paramiko/pkey.py#L151-L162) (and [loading](https://github.com/paramiko/paramiko/blob/23f92003898b060df0e2b8b1d889455264e63a3e/paramiko/pkey.py#L196-L198)).
This PR offers to call Paramiko's PKey class for loading public keys instead of instantiating key subclasses directly.
Closes: #601
=> Use Paramiko's PKey class for loading public keys instead of instantiating key subclasses directly

examples/vendor/nokia/sros/config_mode.py, ncclient/devices/alu.py, ncclient/devices/ciena.py, ncclient/devices/csr.py, ncclient/devices/default.py, ncclient/devices/ericsson.py, ncclient/devices/h3c.py, ncclient/devices/hpcomware.py, ncclient/devices/huawei.py, ncclient/devices/huaweiyang.py, ncclient/devices/iosxe.py, ncclient/devices/iosxr.py, ncclient/devices/junos.py, ncclient/devices/nexus.py, ncclient/devices/sros.py, ncclient/manager.py
This adds ability to dynamicall pass RPC error raise mode and a list of errors (string pattern) to be ignored in RPC replies.
This is more flexible compared to the current method of statically exempting errors within the device handler classes.
=> Adding error handling parameters for RPC replies.

test-requirements.txt
To expand on the rationale for this, `pytest-runner` has been [deprecated upstream](https://github.com/pytest-dev/pytest-runner/tree/v6.0.1?tab=readme-ov-file#deprecation-notice) for some time, and the project is now archived.
It is not required for running the tests via `tox` anyway, so nothing seems to be lost by removing the dependency.
=> Drop the pytest-runner dependency

ncclient/transport/__init__.py
This PR is aim to reduce some unnecessary memory usage during the import of `ncclient.transport` by lazy-loading some submodules only when they are needed.
In file `ncclient/transport/__init__.py`, the following submodules are imported by default:
```python
from ncclient.transport.ssh import SSHSession
from ncclient.transport.tls import TLSSession
from ncclient.transport.unixSocket import UnixSocketSession  # if possible
```
These package cause a ton of unnecessary memory usage when `ncclient.transport` is imported, especially when the user does not use these transport methods.
For example, I only use `UnixSocketSession` in my scenario, but when I import `ncclient.transport`, it also imports `SSHSession` and `TLSSession`, which I never use. This is a waste of memory.
Here is the memory …
=> Lazy-load some submodules inside ncclient.transport only when needed

tox.ini
This fixes testing with `tox` after `test-requirements.txt` was renamed to `requirements-test.txt` in a3566423ae005b41c613d75bdc5fe3435872dbcc.
=> Update tox.ini for test-requirements.txt → requirements-test.txt
